services:
  core.database:
    working_dir: /
    image: "postgres"
    environment:
      POSTGRES_DB: "coredb"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    expose:
        - "5432"
    build:
      context: .
  core.server:
    working_dir: /app
    image: "core/server"
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - ASPNETCORE_URLS=https://*:8081;http://*:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
    - name: web
      target: 8080
      host_ip: 127.0.0.1
      published: "8080"
      protocol: tcp
      app_protocol: http
      mode: host

    - name: web-secured
      target: 8081
      host_ip: 127.0.0.1
      published: "8081"
      protocol: tcp
      app_protocol: https
      mode: host
    expose:
      - "8080"
      - "8081"
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - core.database
    network_mode: host

networks:
  core-network:
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "172.0.0.1"
