version: '3.9'

services:
  core.database:
    working_dir: /
    image: postgres
    environment:
      POSTGRES_DB: "coredb"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    build:
      context: .
  core.server:
    image: core/server
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: ./Dockerfile


