const homeActions = {
	CREATE_ADVENTURE_SUCCESS: "CREATE_ADVENTURE_SUCCESS",
	CREATE_ADVENTURE_FAILURE: "CREATE_ADVENTURE_FAILURE",
	GET_ALL_ADVENTURES_SUCCESS: "GET_ALL_ADVENTURES_SUCCESS",
	GET_ALL_ADVENTURES_FAILURE: "GET_ALL_ADVENTURES_FAILURE",
	UPDATE_ADVENTURE_SUCCESS: "UPDATE_ADVENTURE_SUCCESS",
	UPDATE_ADVENTURE_FAILURE: "UPDATE_ADVENTURE_FAILURE",
	DELETE_ADVENTURE_SUCCESS: "DELETE_ADVENTURE_SUCCESS",
	DELETE_ADVENTURE_FAILURE: "DELETE_ADVENTURE_FAILURE"
};

export default homeActions;