const loginActions = {
	AUTHENTICATE_USER_SUCCESS: "AUTHENTICATE_USER_SUCCESS",
	AUTHENTICATE_USER_FAILURE: "AUTHENTICATE_USER_FAILURE",
	LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
	LOGOUT_USER_FAILURE: "LOGOUT_USER_FAILURE"
};

export default loginActions;