const actions = {
	USER_RESTORE_AUTHORIZATION_DATA: "USER_RESTORE_AUTHORIZATION_DATA",
	USER_CREATE: "USER_CREATE",
	USER_LOGIN: "USER_LOGIN",
	USER_LOGOUT: "USER_LOGOUT",
	CREATE_ADVENTURE: "CREATE_ADVENTURE",
	GET_ALL_ADVENTURES: "GET_ALL_ADVENTURES",
	UPDATE_ADVENTURE: "UPDATE_ADVENTURE",
	DELETE_ADVENTURE: "DELETE_ADVENTURE"
};

export default actions;