const loginActions = {
	LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
	LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
	LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
	LOGOUT_USER_FAILURE: "LOGOUT_USER_FAILURE"
};

export default loginActions;